name: Compilar TWRP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Baixar os arquivos do próprio repositório
      uses: actions/checkout@v4

    - name: Configurar Ambiente Linux e Instalar Ferramentas
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python3 python3-pip

    - name: Clonar a Ferramenta Repo do Gerrit Oficial
      run: |
        mkdir -p ~/bin
        # Clonando o repositório do Gerrit que você mandou e criando o link simbólico
        git clone https://gerrit.googlesource.com/git-repo ~/bin/git-repo
        ln -sf ~/bin/git-repo/repo ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Configurar Git Global
      run: |
        git config --global user.name "lemki_25"
        git config --global user.email "kathlendelimafarias-bit"

    - name: Inicializar Manifesto do TWRP
      run: |
        mkdir -p ../twrp_base
        cd ../twrp_base
        # Usando a URL oficial estável do repositório minimal do TWRP
        repo init --depth=1 --no-repo-verify -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1

    - name: Sincronizar Código-Fonte (Download Pesado)
      run: |
        cd ../twrp_base
        repo sync -j$(nproc) --force-sync --no-clone-bundle --no-tags

    - name: Mover Árvore de Dispositivos para o Local Correto
      run: |
        mkdir -p ../twrp_base/device/motorola/nice
        rsync -arv --exclude='.github' --exclude='.git' ./ ../twrp_base/device/motorola/nice/

    - name: Executar a Compilação (.img)
      run: |
        cd ../twrp_base
        export BUILD_BROKEN_MISSING_OUTPUTS=true
        export ALLOW_MISSING_DEPENDENCIES=true
        export DISABLE_RELEASE_CONFIG_VALIDATION=true
        source build/envsetup.sh
        lunch twrp_nice-eng
        mkdir -p out/target/product/nice
        cp device/motorola/nice/prebuilt/kernel out/target/product/nice/kernel
        cp device/motorola/nice/prebuilt/dtb.img out/target/product/nice/dtb.img
        mka vendorbootimage

    - name: Salvar o arquivo .img gerado
      uses: actions/upload-artifact@v4
      with:
       name: TWRP-Nice-Final
       path: /home/runner/work/twrp_device_motorola_nice/twrp_base/out/target/product/nice/vendor_boot.img
       if-no-files-found: warn
