name: Compilar TWRP Moto G86

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do Repositório
      uses: actions/checkout@v4

    - name: Configurar Ambiente Linux
      run: |
        sudo apt-get update
        sudo apt-get install -y gperf gcc-multilib g++-multilib libc6-dev libncurses5-dev libncursesw5-dev libx11-dev zlib1g-dev libxml2-utils xsltproc unzip bc bison build-essential ccache curl flex g++ rsync libssl-dev python3

    - name: Maximizar Espaço em Disco
      uses: easimon/maximize-build-space@v8
      with:
        root-reserve-mb: 1024
        swap-size-mb: 10240
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'

    - name: Baixar Ferramenta e Inicializar Manifesto (Tudo Junto)
      run: |
        # Instala o utilitário do sistema
        sudo apt-get update && sudo apt-get install -y repo
        
        # Cria a pasta e entra nela
        mkdir -p twrp
        cd twrp
        
        # Limpa COMPLETAMENTE qualquer regra de redirecionamento para que o Git rode puro
        git config --global --unset-all url."git@github.com:".insteadOf || true
        git config --global --unset-all url."https://github.com/".insteadOf || true
        
        # Configura as credenciais locais exigidas
        git config --global user.name "kathlendelimafarias-bit"
        git config --global user.email "kathlendelimafarias@gmail.com"
        
        # Inicializa o manifesto isolando a revisão de código interno
        repo init --depth=1 --no-repo-verify -u https://github.com -b twrp-14.0


    - name: Sincronizar Arquivos do Android 14 (Download Longo)
      run: |
        cd twrp
        ~/bin/repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

    - name: Clonar a Sua Device Tree
      uses: actions/checkout@v4
      with:
        path: twrp/device/motorola/nice

    - name: Executar a Compilação (Build)
      run: |
        cd twrp
        export ALLOW_MISSING_DEPENDENCIES=true
        source build/envsetup.sh
        lunch twrp_nice-eng
        mka recoveryimage -j$(nproc --all)

    - name: Salvar o Arquivo .IMG Pronto
      uses: actions/upload-artifact@v4
      with:
        name: TWRP-MotoG86-Nice
        path: twrp/out/target/product/nice/*.img
